config/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'continents', views.ContinentViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name="index" ),
    path('country/', include('core.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls'))
]

core/urls.py
from django.urls import path
from core.views import *

app_name='core'

urlpatterns = [
    path('create/', CreateCountry.as_view(), name="create" ),
    path('list/', ListCoutryView.as_view(), name="country_list" ),
    path('get_places/', get_places, name='get_places')
]

core/models.py
from django.db import models
from django.urls import reverse 
# Create your models here.

class Continent(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "Continent"

    def __str__(self):
        return self.name

class Country(models.Model):
    name = models.CharField(max_length=255)
    continent = models.name = models.ForeignKey('Continent', on_delete=models.CASCADE, blank=True, null=True)
    class Meta:
        verbose_name_plural = "Country"
        
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('coutry_list', kwargs={'pk':self.pk})

core/forms.py
from django import forms
from . import models

class CoutryForm(forms.ModelForm):
    class Meta:
        model = models.Country
        fields = ('name',)

core/views.py
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic   import CreateView, TemplateView, ListView
from django.http import HttpResponse

from rest_framework import viewsets

from core.models import *
from core.forms import CoutryForm
from core.serializers import *

import json

class ContinentViewSet(viewsets.ModelViewSet):
    queryset = Continent.objects.all().order_by('id')
    serializer_class = ContinentSerializer

def get_places(request):
    if request.is_ajax():

        q = request.GET.get('term', '')
        print(q)
        continents = Continent.objects.filter(name__icontains=q)
        result = []
        for continent in continents:
            continent_json = {}
            continent_json = continent.name 
            result.append(continent_json)
        data = json.dumps(result)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

# Create your views here.
class Home(TemplateView):
    template_name = 'index.html'

class CreateCountry(CreateView):
    model = Country
    form_class = CoutryForm
    template_name = 'form.html'
    success_url = reverse_lazy('core:create')

    def form_valid(self,form ):    
        
        """If the form is valid, save the associated model."""
        continent = Continent.objects.get(name=self.request.POST.get('continent'))
        self.object = form.save(commit=False)
        self.object.continent = continent
        self.object.save()
        return super().form_valid(form)


    def get_success_url(self):
        if self.success_url:
            messages.success(self.request, 'Criado com successo')
            return self.success_url.format(**self.object.__dict__)
        else:
            raise ImproperlyConfigured("No URL to redirect to. Provide a success_url.")

class ListCoutryView(ListView):
    pass

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Maps</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>
            <!-- jQuery UI !-->
            <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
        <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
        
    </head>
    <body>
        {% include "navbar.html" %}
        
        {% if messages %}    
        {% for message in messages %}        
        <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible" {% endif %} role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
            
            {% block content %}
            
            {% endblock content %}

            
</body>
</html>

templates/form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
<section>
    <div class="row" style="padding-top:8%">
        <div class="col-6 offset-3">
            <form method="POST" novalidate>
                {% csrf_token %}
                {% for hidden  in form.hidden_fields  %}
                {{hidden}}
                {% endfor %}
                {% for field in form.visible_fields  %}
                    <div class="form-group">
                        <label for="{{ firld.id_for_label}}">{{field.label}}</label>
                        {{field|add_class:'form-control'}}
                    </div>                 
                    {% for error in field.errors  %}
                        <span class="help-block text-danger">{{error}}</span>
                    {% endfor %}
                {% endfor %}
                <div class="ui-widget">
                    <label for="continent">Continent: </label>
                    <input class="form-control" name="continent" id="continent">
                </div> 
                <div class="form-group">
                    <input class="btn btn-primary" type="submit" value="Create">
                </div>
            </form>
        </div>
    </div>
</section>

<script>
    
    
$(function() {
  $("#continent").autocomplete({
    source: "{% url 'core:get_places' %}",
    minLength: 1,
  });
});
    
    function AutoCompleteSelectHandler(event, ui){
        var selectObj = ui.item
    }
</script>
{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="container">

        <a class="btn btn-success active" href="{% url 'core:create'%}">Create country</a>
    </div>
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-dark bg-dark">
    <a href="#" class="navbar-brand">Maps</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-taget="#navbarSupported">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupported">
        <ul>
            <li>

            </li>
        </ul>
</nav>